### ISSUE TITLE
Add Save As function

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#108]
Add a Save As function to save the current source as a new file, possibly even in a different project.

**Comment by phated** [comment]
Pushing this issue back and breaking it into smaller issues, as it has 5 main parts that I can see.
- Save an unsaved ("untitled") file as a named file (addressed in #107)
- Save a file as a different name
- Save a file into a different project
- Add a "Save As" button into the UI
- Add a "Save As" key command

**Comment by PropGit** [comment]
Agreed.

**Comment by urbantumbleweed** [comment]
This issue is split apart into 4 issues. For more information please go the sub-issues. #152, #153, #154, #155
