### ISSUE TITLE
Line numbers collide with vertical line

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#111]
It seems the right-shift of text in the editor doesn't move over far enough for longer listings.  When it reaches > 99 lines, the higher-numbered lines' line number indicators overlap the vertical separator line between the editor and the project/file list.

The effect is most visible at lines in the 300s.  It's uncomfortably close to the fading shadow effect.

Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/1266318/7972886/e86253e4-0a04-11e5-9da2-bcb0049d52e6.png)

**Comment by urbantumbleweed** [comment]
Just a friendly reminder that we need a screenshot for this issue.  Once that's in, I'll reassign.

**Comment by PropGit** [comment]
@urbantumbleweed, done... see first comment.

**Comment by phated** [comment]
Thanks, reassigning to @drquinn
