### ISSUE TITLE
Apply flux architecture patterns to remove state from views

### ISSUE THREAD

**Issue by phated** [parallaxinc/Parallax-IDE#115]
The library I've been using is https://www.npmjs.com/package/alt

**Comment by PropGit** [comment]
I can't prioritize this as I don't understand what it is or how it affects things.

**Comment by phated** [comment]
This is a top priority, as discussed during the last demo call.  I've marked it as priority 1

**Comment by phated** [comment]
Closed now that #137 #141 and #142 are merged.
