### ISSUE TITLE
Filter out all 'cu' ports

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#116]
Remove (filter out) all 'cu' type ports from the COM port list any time the list is presented to the user.

**Comment by phated** [comment]
Should this also address Bluetooth ports?

**Comment by PropGit** [comment]
For now, yes.  We do have some people that use a bluetooth device to program the BASIC Stamp wirelessly, but it's rare.  We'll readdress the filtering scheme again later to allow the user more control over this.  For now, just filter out all 'cu' and bluetooth ports.

**Comment by 2fast2fourier** [comment]
I think we can safely ignore the `Bluetooth-Incoming-Port` and `Bluetooth-Modem` OSX virtual devices, they shouldn't ever represent a BS2 and can cause a delay when opening the port. Bluetooth serial devices (SPP) should come up under a different name, I'll verify this with a BT serial adapter I use for MCU comms.

**Comment by PropGit** [comment]
That sounds good.

**Comment by phated** [comment]
Closed by https://github.com/parallaxinc/ChromeIDE/pull/135
