### ISSUE TITLE
Enumerate and scan ports upon opening Identification/Download dialog

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#118]
[Related to issue #74]

Make the Identification and Download dialog enumerate and scan all ports upon display (activation).

The "Reload Devices" button can still be used later by the user, but should not be required at the start.  Note this button is renamed by issue #119.

**Comment by phated** [comment]
Fixed by https://github.com/parallaxinc/ChromeIDE/pull/137
