### ISSUE TITLE
Tab key indents selected block

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#120]
Implement multi-line selection indention via tab key.
- Tab - Indent block (Inserts spaces to align with absolute multiples of 2)

**Comment by phated** [comment]
@PropGit do you have a list of items you want tackled as part of this? or bugs you have found with indent?

**Comment by PropGit** [comment]
@phated Yes.
**BUG** Selecting a block of text and then pressing Tab replaces all of selection with "tabbed" whitespace.

**Example**

**Selected text:**
![image](https://cloud.githubusercontent.com/assets/1266318/8245933/b9fa4182-15ea-11e5-801f-98f8a6604939.png)

**Tabbed result:**
![image](https://cloud.githubusercontent.com/assets/1266318/8245942/d37fc6ae-15ea-11e5-9aa4-86f337dbba47.png)

**Expected result:**
![image](https://cloud.githubusercontent.com/assets/1266318/8245949/f5e995c6-15ea-11e5-9efe-96744972ed59.png)
