### ISSUE TITLE
Shift-Tab outdents selected block

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#121]
Implement multi-line selection outdention via Shift-Tab key combination.
- Shift-Tab - Outdent block (Deletes spaces to align with absolute multiples of 2)

**Comment by phated** [comment]
@PropGit do you have a list of items you want tackled as part of this? or bugs you have found with outdent?

**Comment by PropGit** [comment]
@phated Yes.
  **BUG** Selecting a block of text and then pressing Shift-Tab removes _all_ whitespace, slamming the poor text ferociously into the left margin instead of removing just the previous tab position's-worth of whitespace.

  _Example_

  **Selected text:**
![image](https://cloud.githubusercontent.com/assets/1266318/8245883/015874be-15ea-11e5-8715-8e9ed03eecb2.png)

  **Shift-Tabbed result:**
![image](https://cloud.githubusercontent.com/assets/1266318/8245887/13d3a208-15ea-11e5-8339-2f296941eeaf.png)

  **Expected result:**
![image](https://cloud.githubusercontent.com/assets/1266318/8245890/2ab9b9c6-15ea-11e5-98ef-7071aabeb0d0.png)
