### ISSUE TITLE
Add Ctrl-F4 key combination to replace current found selection and then find next

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#123]
- Ctrl-F4 - Perform replace and find next
  - Just like F4, but after the replace, moves to the next found selection (ie: it's like pressing F4 followed by F3)

**Comment by phated** [comment]
Let's target completion of this with the default CodeMirror UI.  If it is desired to be improved upon later, we can open a UI/UX issue.
