### ISSUE TITLE
Update Identify Feature

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#128]
Make Identify feature (currently attached to "Reload Devices" button) a separate function if not already.
- Add shortcut keys F6 and also Ctrl-I to activate the Identify feature
- This displays the Identify dialog (if not already displayed) and performs the Identification process on all available ports, showing the results in the dialog
- Pressing the "Reload Devices" button (which is being [renamed to "Refresh"](https://github.com/parallaxinc/ChromeIDE/issues/119)), or F6 or Ctrl-I again (while dialog is on-screen) performs an Identification process again.

**Comment by PropGit** [comment]
Does this need to be broken into multiple issues?  There's also a UX/UI element to activate the Identify function, but it was not specified here.

**Comment by phated** [comment]
@PropGit I think that would be good.  Would you like me to do that now?

**Comment by PropGit** [comment]
Yes please.  From now on, I'll try to enter issues with a finer grain.  I'm used to thinking of these things as so interrelated that they don't make sense to me as separate items, but I think I understand your perspective now.

**Comment by phated** [comment]
@PropGit it seems that there are only 2 issues remaining to this functionality (the UI element and the key combination).  Do you agree?  I've split those 2 issues out.

**Comment by PropGit** [comment]
Yes, as long as the Identify function already exists as a separately-callable function, and not as an intrinsically integrated part of the download function.  ie: Download should call Identify as the first part of it's operation, which means that the overlay activated by #157 and #158 can call Identify (also) but then simply update the display and wait for user input (to Identify again or close the overlay).

**Comment by urbantumbleweed** [comment]
This issue is being broken up into two smaller, but related issues.  One to create key shortcut and another to create a UI component.  Issues are #157 and #158
