### ISSUE TITLE
Changing Name from "Chrome IDE" to "Parallax IDE"

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#151]
We are officially changing the name of this project as the subject says.

This means
- We need to change occurrences of "Chrome IDE" in the application and the repository sources (like readme.md and the releases' QuickStart Installation notes) to "Parallax IDE"
- I will be changing the repository soon.

NOTE: historical items (like previous release archives) do not need to change; they can remain as is, but future such items should carry the new name.

**Comment by PropGit** [comment]
I can change the repository name right now if you're ready.  I'll wait until I see a response.

**Comment by phated** [comment]
@PropGit I think we are ready for you to change the name

**Comment by PropGit** [comment]
Okay, done!  The official name is "Parallax IDE" but the repo is "Parallax-IDE"

**Comment by phated** [comment]
@PropGit it seems you need to change the Travis-CI hook now, as it is trying to get from ChromeIDE still.

**Comment by PropGit** [comment]
@phated Sorry, need help on this one.  Can't find how I did this the first time and if I log into Travis, it thinks its the first time I've been there.  Email me if need be.

**Comment by phated** [comment]
@PropGit I started making a series of images to walk you through this, but it seems that Travis-CI has already done the updating behind the scenes.  I didn't know they started doing that.

**Comment by PropGit** [comment]
Is Travis CI working now?

**Comment by phated** [comment]
@PropGit yep, it sorted itself out! :astonished:
