### ISSUE TITLE
Save As - Overwrite Protection (Prompt)

### ISSUE THREAD

**Issue by jeffam70** [parallaxinc/Parallax-IDE#168]
As it relates to Issues #152 and #153 (Save As overlay), add a feature that protects against accidental overwriting.

On the Save As overlay, when the user clicks the Save As button, the system should always prompt with a confirmation overlay if the filename matches an already existing file in the target folder.  The prompt should say, "File 'filename' already exists. Overwrite anyway?" and should have an Overwrite and a Cancel button.

**Comment by phated** [comment]
I think this is a bit too much to add to this sprint.  Let's slate it for the next sprint

**Comment by PropGit** [comment]
Okay.

**Comment by urbantumbleweed** [comment]
@monteslu to address this issue you are going to want to look at the following files:

1. [src/views/save-overlay.js](https://github.com/parallaxinc/Parallax-IDE/blob/master/src/views/save-overlay.js)
1. [src/plugins/overlays.js](https://github.com/parallaxinc/Parallax-IDE/blob/master/src/plugins/overlays.js)
1. [client.js](https://github.com/parallaxinc/Parallax-IDE/blob/master/client.js)

I suspect that the actual logic will go in src/views/save-overlay.js

**Comment by PropGit** [comment]
Verified done.
