### ISSUE TITLE
Print shows menu system on first page

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#181]
The print function still shows the menu _chrome_ on the first page of the printout if the menu happened to be left expanded.

![image](https://cloud.githubusercontent.com/assets/1266318/8585558/416f2b48-2598-11e5-83b9-4497bc9ac163.png)

**Comment by phated** [comment]
Added to Sprint 7 because it was a quick fix

**Comment by PropGit** [comment]
Verified fixed!
