### ISSUE TITLE
Implement TAB in terminal backing store

### ISSUE THREAD

**Issue by 2fast2fourier** [parallaxinc/Parallax-IDE#191]
While implementing features in transmit pane, we discovered an issue TAB feature from parallaxinc/Parallax-IDE/issues/75. It is being processed correctly in the receive stream, but the console store and UI are not updated to reflect new state. This ticket is to track implementation of that feature.

**Comment by phated** [comment]
Added to Sprint 7 because it only took 15 minutes.
