### ISSUE TITLE
Holds port open after failure to identify

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#195]
Parallax IDE needs to close the port after a failure to identify or download.  See [video for example](https://drive.google.com/file/d/0B0tev9Y3WaL4UzlGYlB5TnY3UWs/view?usp=sharing) that uses the BSE's Identify feature and Parallax IDE's Identify feature.  At the [end of this video](https://drive.google.com/file/d/0B0tev9Y3WaL4TFR2U1RrQUY0Z3c/view?usp=sharing) you can see how the port is held open only after a failure to identify.

This problem may also be preventing Parallax IDE itself from reopening the port upon the next Identify/Download operation.

NOTE: Parallax IDE should have been able to identify during this case, but it also has a problem handling serial data entering the receive buffer before (or right after) the reset condition is issued, as noted by Issue #194.

**Comment by phated** [comment]
This should be fixed with dependency updates.

**Comment by PropGit** [comment]
Verified correct.  Yay!
