### ISSUE TITLE
Save As Overlay: Put cursor to right of current file name

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#204]
Issue #152, in Sprint 6 indicated that [the field should be focused and the cursor should be to the right of the file name](https://github.com/parallaxinc/Parallax-IDE/issues/152#issuecomment-115035841).  

The cursor still appears to the left of the file name upon activation of the Save As overlay.  Please fix it so that the cursor appears to the right of the current file name every time the overlay is activated.

**Comment by PropGit** [comment]
**[Bug Introduced]**
The solution employed to solve this issue causes cursor navigation to fail while editing the filename.

Clicking in the field (to place the cursor anywhere but at the end), cursor keys, HOME, Ctrl and/or Shift + cursor key combinations (and more) are thwarted, forcing the user to edit the whole filename only from the right side.  Any cursor movement is undone and the cursor is once again returned to the right side of the filename.

**Comment by phated** [comment]
@PropGit I am unable to reproduce what you are explaining.  None of the code I modified would cause it either

**Comment by PropGit** [comment]
@phated - Whoa... is this perhaps a Windows thing or a Chrome 45 thing?

Wait.  I built off of the break-compat branch; perhaps that's the source of the problem.  Maybe it's a non-issue for the pre-release you're building today?

**Comment by phated** [comment]
@PropGit I am using Chrome 45 on my mac.  I will try to get a windows VM running but the cursor stuff shouldn't be platform dependent.  The break-compat branch had the same changes in it.

**Comment by PropGit** [comment]
@phated - I'll make a video then.

**Comment by PropGit** [comment]
@phated - Here's [a demo video](https://drive.google.com/file/d/0B0tev9Y3WaL4UW84bXZCLWJJSTQ/view?usp=sharing) of the symptoms I'm seeing.

**Comment by phated** [comment]
@PropGit thanks for the video.  I did a fresh install and build and am able to see this behavior now.  Working on a fix before the release.  Thanks for catching this and showing me.

**Comment by phated** [comment]
@PropGit I've pushed a fix to the master branch.  Can you please build from master, test and let me know if it is working?  If so, I will cut the release

**Comment by PropGit** [comment]
@phated - Yes.  I will do that now...

**Comment by PropGit** [comment]
@phated - Success!  It works perfectly now, thank you!

**Comment by phated** [comment]
@PropGit Hooray!  Cutting the release shortly

**Comment by PropGit** [comment]
Verified fixed.
