### ISSUE TITLE
Automatic Save As fails after new session

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#206]
New file's status is forgotten between Parallax IDE sessions.
- Create a new file
- Don't save it
- Close Parallax IDE
- Start Parallax IDE
- [Source is displayed, as expected]
- Save
  -  Parallax IDE does a Save operation (as _untitled#_) instead of forcing an automatic Save As operation and dialog.

**Comment by phated** [comment]
This will be fixed by the refactor

**Comment by PropGit** [comment]
Verified correct.
