### ISSUE TITLE
Automatic Save Prompt fails for new files after session

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#207]
[This is likely related to Issue #206] 
New file's status is forgotten between Parallax IDE sessions - leading to loss.
- Create a new file
- Don't save it
- Close Parallax IDE
- Start Parallax IDE
- [Source is displayed, as expected]
- Select another file from the Project/File view
- Parallax IDE immediately displays selected file without prompting to save the new and unsaved file first
  - The new and unsaved file is lost forever

NOTE: When this is fixed, make sure the solution doesn't negatively affect the scenario where the user has modified an existing file, closed Parallax IDE, started Parallax IDE and navigated away to another file- this currently works perfectly as expected.

**Comment by phated** [comment]
Due to the filesystem refactor, this should be fixed in sprint 8.

**Comment by PropGit** [comment]
Looking forward to it.

**Comment by PropGit** [comment]
Unable to fully test this because of issues #231, #232, #234, #235, and #236.

**Comment by PropGit** [comment]
Verified fixed.
