### ISSUE TITLE
Deleting file causes phantom new file and Save As dialog

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#209]
**Problem**
- Make sure there's at least two files in the Project/File View
- Select one of the files
- Choose the Delete menu option
- Answer the warning prompt with _Yes_
- [The editor blanks out (expected) and toast appears saying delete of file was successful (expected)]
- Select another file
- Parallax IDE unexpectedly prompts with "Do you want to save the changes you made to New file?"  Also, even more incorrect, is that the filename field is filled with the name of the file you just selected.

**Solution**
- Silently skip the "Do you want to save..." prompt if the _new and unsaved_ file in the editor contains only whitespace.

**Comment by phated** [comment]
The refactor handles this, but we only check the text content has no length.  If you were to type a space or tab, it would prompt.  Is that not desired behavior?

**Comment by PropGit** [comment]
Can you wrap the text content in a trim function so the check would equate the whitespace-only content to no length?  That would achieve the results we want.

**Comment by phated** [comment]
Yep, can do.  That's a really quick change and will be fixed with the refactor.

**Comment by PropGit** [comment]
Verified correct.
