### ISSUE TITLE
Debug Terminal: TX/RX - Increase activity visibility

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#213]
To increase communication activity visibility on the TX/RX indicators:
- Increase the minimum time the TX/RX indicators are _lit_ to about 100 ms; assuming it's currently limited to a minimum time of about 50 ms as requested in [Issue # 78](https://github.com/parallaxinc/Parallax-IDE/issues/78#issuecomment-110996974).
- After the above time expires (TX/RX lit), force an _unlit_ moment of no less than about 25 ms (before lighting again) so that the TX/RX indicators have a visible blink even when a continuous stream of data is arriving at a high rate of speed.

**Comment by 2fast2fourier** [comment]
I've submitted this as PR #302, but with a minimum unlit time of 50ms. When testing the flashing on a fast loop, 50ms looked a lot cleaner than a 25ms period.

**Comment by PropGit** [comment]
@2fast2fourier - Thank you!

**Comment by PropGit** [comment]
Verified fixed on Rx, but Tx seems to not blink at all.  Opened a new issue #310.
