### ISSUE TITLE
User configuration sometimes doesn't always save changes

### ISSUE THREAD

**Issue by phated** [parallaxinc/Parallax-IDE#231]
I'm not sure why this is happening, but there can be work done int the user configuration module dependency that makes this better a lot better.  This should be tackled ASAP.

I usually notice this the most when changing between projects or files and closing the app within a short period of time.

Ref #208 as a sibling issue

**Comment by PropGit** [comment]
This is much better now, but there are still occasions where the state fails to save (or restore) as described in new Issue #248.
