### ISSUE TITLE
Temporary source reopens only every other time

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#234]
New unsaved source code reopens in the app _only every other time_.  [Watch this video](https://drive.google.com/file/d/0B0tev9Y3WaL4UWI4N09RblhzZ3M/view?usp=sharing) for a demonstration.

This may be related to issue #231, #232, #235, and #236.

**Comment by phated** [comment]
Duplicate of #231

**Comment by PropGit** [comment]
Verified fixed via the same steps described in the demo video.
