### ISSUE TITLE
Trouble creating and saving new file source

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#235]
App v0.7.0's temporary file or file storage logic seems to be broken.

[Watch this video](https://drive.google.com/file/d/0B0tev9Y3WaL4QTBFWG5SVUtwMVk/view?usp=sharing) for a demonstration of my struggles just to create and save new source.

This may be related to issue #231, #232, #234, and #236.

**Comment by phated** [comment]
Most likely a duplicate of #231

**Comment by PropGit** [comment]
Verified fixed using the same steps as in the demo video.
