### ISSUE TITLE
Hide the "Don't Save" button when discarding a file isn't a desired behavior

### ISSUE THREAD

**Issue by phated** [parallaxinc/Parallax-IDE#247]
Currently, if a file is a brand new (unsaved) file, the Save/Save As prompt has a "Don't Save" button.  This is desired when a user attempts to change from a new file to a previously saved file and is prompted to save.  However, this is incorrect UI behavior when the user is just using the Save/Save As functionality of the editor.  We need to hide the "Don't Save" button when we are not in the "Changing File" mode.

**Comment by PropGit** [comment]
NOTE: This is a new behavior (bug) in v0.7.1; it did not behave this way in v0.7.0 as you can see about 20 seconds into [this video](https://drive.google.com/file/d/0B0tev9Y3WaL4QTBFWG5SVUtwMVk/view?usp=sharing) that was recorded for issues #235.

It seems to only happen incorrectly when it is a new file and either the Save or Save As operation is user-activated.  After it is saved, an Save As operation shows the right dialog (with no "Don't Save" button).

**Comment by PropGit** [comment]
Verified fixed.  However, this has led to a side effect noted in issue #268.
