### ISSUE TITLE
New files get default directives

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#253]
We currently don't have Stamp and PBASIC directive quick-access buttons - we need to ease the pain of users creating new files.

For a temporary time, we want all new files to automatically have the default Stamp and PBASIC directives inserted into them.

```
'{$STAMP BS2}
'{$PBASIC 2.5}


```

**Comment by phated** [comment]
Note: this will cause the user to **always** be prompted to save a new file because it now has text in it.

**Comment by PropGit** [comment]
Understood; we accept those results as having the directives are normally what the user wants as he/she is starting to write new code anyway.

This is a temporary measure that will be replaced with a different, although similar, method of swiftly getting the directives in-place.  We may or may not choose to address the non-blank-but-still-disposable source issue in a nicer way in the future.

**Comment by PropGit** [comment]
UPDATE: I updated the first post's code to include two blank lines.

Is it possible to place the cursor at the start of the 4th line (2nd blank line) when, and only when, this text is placed in the edit by the New operation?

**Comment by PropGit** [comment]
Verified done.
