### ISSUE TITLE
Force sync now?

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#280]
[syncFileSystem questions related to issue #238]

Can we force a sync with syncFileSystem at will?
- If a file or project was created or updated, is the app relying on syncFileSystem to perform the sync operation whenever it feels like it, or do we tell it to sync now?
- If the former, can we tell it to sync now?

FYI: These questions are due to the noticeable and indeterministic delays in updating the files and projects.

**Comment by urbantumbleweed** [comment]
The short answer to this is no.  The updating is performed within syncFileSystem and our application has no way to initiate synchronization activity. We are able to get the sync status on existing files.

The api allows for us to write to, read from, listen for events, select a conflict strategy, and check status... that's really about it.  The ability to force actions like a synchronization event are out of our control.

We don't work directly with Google Drive.

Google controls the timing of when synchronization events occur across application instances. This means it is possible for a user to update a file on one client, save the file and then open on another client and have different versions of the file. It depends on Google timing.
