### ISSUE TITLE
Sync Settings

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#286]
[Planning and future thinking related to issue #238]

For syncFileSystem to work, the app must be installed from CWS (which gives it the same App ID) and the user's Google Account must have the _Apps_ preference checked in the _Advanced sync settings_.

How does this affect the syncFileSystem feature when we deploy to Android and iOS?  Neither will use CWS, and Chrome mobile doesn't have sync settings.

**Comment by urbantumbleweed** [comment]
When we deploy on Android and IOS the use of parallaxIDE will be local to the device. These would not be sync'd from use of ChromeBooks and desktop computers. In order for that synchronization to occur an additional service would be needed.
