### ISSUE TITLE
Test and Enhance to Identify and Download to BS2e, BS2sx, BS2p24, BS2p40, and BS2pe

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#291]
Verify that the app can identify and download to BS2e, BS2sx, BS2p24, BS2p40, and BS2pe modules.

At this point in time, it appears that this functionality is already built-in, or is close to being complete for Identification.

The current app may or may not be able to handle the normal single-slot download properly.  Please verify as part of this issue.  Note that Issue #292 (to be implemented at a later time) addresses multi-slot programming.

**Comment by 2fast2fourier** [comment]
@PropGit I'm working through these modules now, and encountered something odd with BS2e. According to the BASIC Stamp Programming Protocol 1.1 docs, BS2e identification should be a sequence of:
- Send `e` (`0x65`)
- Receive echo `e`
- Receive version byte, where `0x65`is 1.0. No other versions are mentioned.

This BS2e is Rev E, but I'm seeing a `0x67` response for the version step. Is this just a newer revision that isn't documented here?

**Comment by PropGit** [comment]
@2fast2fourier - The hardware revision doesn't relate in any direct way to the firmware version; so just ignore the "Rev E" you see on the hardware.

The firmware of many modules has been revised since that document was written.  Here's a current list of expected firmware versions (but _every_ version from v1.0 through the listed version should be supported by the app; ie: identify and download to all old versions too).  None of the firmware versions have changed the download protocol of that module in any way that would prevent proper download.

BS2 - v1.0
BS2e - v1.2
BS2sx - v1.3
BS2p24/40 - v1.7
BS2pe24 - v1.4

The 0x67 (character 'g') represent's firmware version 1.2 for the BS2e.

**Comment by PropGit** [comment]
_[CORRECTION]_

All versions 1.0 through the latest listed in the previous post should be identifiable and downloadable from the app with the exception of the BS2p... that should only support v1.2 through v1.7.  It's not the way I'd want it, but it's the way it is.

**Comment by PropGit** [comment]
Verified working.
