### ISSUE TITLE
"New Version" notice snubbed

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#309]
@phated - Upon auto-updating, the "New Version" notice for v0.10.0 seems to be snubbed by the new permission that Chrome to auto-disabled the app until user intervention. 

![image](https://cloud.githubusercontent.com/assets/1266318/10645540/19ec71dc-77e3-11e5-920f-7b0c528962e5.png)

When the user accepts the new permission (Re-enables the app), the New Version notice for v0.10.0 is still not shown.

Can we fix this before making v0.10.0 public?

**Comment by phated** [comment]
Chrome issue that causes this bug https://code.google.com/p/chromium/issues/detail?id=480926

**Comment by PropGit** [comment]
@phated - thanks.  After the discussion and considerations, I'm closing this issue as a "won't fix" item.  It may correct itself (ie: Google) later anyway.
