### ISSUE TITLE
Release the BS2 tokenizer as open source.

### ISSUE THREAD

**Issue by phated** [parallaxinc/Parallax-IDE#34]
As discussed with @PropGit, we will need this available before the end of Sprint 2.

**Comment by phated** [comment]
@PropGit what is the status of this?  We are going to need to start implementing this week.

**Comment by PropGit** [comment]
Working on this today.

**Comment by PropGit** [comment]
For now, I only pushed a light from of the [PBASIC Tokenizer project](https://github.com/parallaxinc/PBASIC-Tokenizer).  The branch to start from is Dev-Version-1.3.  @phated , @monteslu , and @jacobrosenthal , you have push access to this repository.  I will be adding a lot to this project as soon as I can.

**Comment by phated** [comment]
I believe we can close this now.  Thanks @PropGit
