### ISSUE TITLE
Display file saved/unsaved state next to filename in sidebar listing.

### ISSUE THREAD

**Issue by phated** [parallaxinc/Parallax-IDE#51]
This could be represented by green and red dots next to filenames.

**Comment by PropGit** [comment]
After some thought, I think it may be best to use
- an icon of a pencil writing something (red, perhaps) when the file has been edited but unsaved by user
- no icon (just blank) when the file has not been edited (or was saved by the user)

**Comment by phated** [comment]
@PropGit I tried getting your suggestions to work, but couldn't easily within the current implementation of the sidebar and I didn't think it was pertinent to completely redo it.

**Comment by PropGit** [comment]
Okay, let's focus on other issues at this point.

**Comment by phated** [comment]
To clarify, I've implemented as originally noted in the issue because it was straightforward to add, but the icons, etc from the suggestion were harder to get right.

**Comment by PropGit** [comment]
Thanks!  I was wondering that and hoping that was the case.
