### ISSUE TITLE
Create icons for app

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#53]
Create icons for editor project "ChromeIDE." 
- 16 x 16
- 48 x 48
- 128 x 128

.png format.

**Comment by PropGit** [comment]
Can you show me examples of where these icons would appear?  16 x 16 is very constraining; hard to convey much there.  Need to know context.

Also, is it full 32-bit color (24-bit RGB + 8-bit alpha)?

**Comment by phated** [comment]
I believe places the icons appear are outlined at https://developer.chrome.com/apps/manifest/icons

Yes, full 32-bit color is correct

**Comment by PropGit** [comment]
Thanks, that helps a lot.

**Comment by PropGit** [comment]
We've created many icon (ideas) for this app and have settled on these for now.  Can you include these in the repo and in the next builds?

[EDIT: Replaced former icons with these more rounded ones]

![pchip-rounded-128](https://cloud.githubusercontent.com/assets/1266318/6987439/da2b5a8e-d9fb-11e4-9771-6bd462ef670a.png)

![pchip-rounded-48](https://cloud.githubusercontent.com/assets/1266318/6987442/dcd4a718-d9fb-11e4-8e1c-b144db039840.png)

![pchip-rounded-16](https://cloud.githubusercontent.com/assets/1266318/6987443/de6a1db0-d9fb-11e4-9f56-1a2bc1bbdea8.png)
