### ISSUE TITLE
Debug Terminal: Support for all defined characters

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#75]
Add support for all defined characters (visible and control characters) as defined in the **Transmit Pane** and **Receive Pane** sections of the [Debug Terminal](https://docs.google.com/document/d/1u0L0WTVU-jfvN4H56efHdBhNYTbObEX72Bn7Fc2RxwE/edit?usp=sharing) document.

**Comment by PropGit** [comment]
NOTE: The Bell control character code (7) will not be implemented at this time due to issues on different platforms.  ASCII code 7 will simple be parsed and ignored (no effect) until possibly a later time if this can be resolved.

**Comment by PropGit** [comment]
NOTE: The [Debug Terminal](https://docs.google.com/document/d/1u0L0WTVU-jfvN4H56efHdBhNYTbObEX72Bn7Fc2RxwE/edit?usp=sharing) document has been updated as of yesterday (see bottom of file) to give a better overall description of the auto-scrolling or not-auto-scrolling moments.

**Comment by phated** [comment]
Currently, all but cursor-position, cursor-position-x, cursor-position-y and collapsing CR,LF are implemented. Those will be addressed after the underlying filesystem architecture is completed, as it is blocking some UI work.
