### ISSUE TITLE
Debug Terminal: Tx/Rx Indicators

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#78]
Add Tx and Rx activity indicators for the Debug Terminal.

The Tx (transmit) and Rx (receive) indicators should be somewhere near the terminal itself.  They each individually flash once for every block of data transmitted or received.

More information may be read in the **Settings** section of the [Debug Terminal](https://docs.google.com/document/d/1u0L0WTVU-jfvN4H56efHdBhNYTbObEX72Bn7Fc2RxwE/edit#) document.

**Comment by urbantumbleweed** [comment]
@PropGit I wanted to reach out to you regarding how the RX/TX indicator elements are to be implemented.  There seems to be some questions about how this element is to appear.  Could you provide us with a note about it's role in the user experience and your thoughts about it might look or where it should go?  Screenshots, mocks or wireframes would be excellent.

If there are any further questions I'll let you know.

**Comment by PropGit** [comment]
@urbantumbleweed I'm somewhat open to suggestions here, but we definitely need to open up some area on screen where this and a few other terminal-related controls can reside.  Somewhere that is visible only when the Debug Terminal is visible.

Here's a crude mock-up of one possibility.  The circles next to TX and RX are like LED lights.  They should light up when there's related activity.

![image](https://cloud.githubusercontent.com/assets/1266318/8099856/4f05f9da-0fb8-11e5-9677-ba83f780cd7c.png)

The point of these is to provide a quick visual indication that some data was received or transmitted as there are many cases when data can move but there's no visual change to the textual display in the Debug Terminal.  Without these, it's very possible to miss the fact that data is moving; leading to unfortunate debugging adventures.

For any data movement event, the appropriate indicator should light up for a minimum of about 50 ms so that the user can see that something happened (even if it was just one character received at 3 Megabaud that caused it to light).

On our development boards, we use blue LEDs for Rx and red LEDs or Tx.  I think using this color scheme would be good for consistency.

NOTE: Another idea is just to make the TX and RX labels themselves light up (change color) when a data movement event happens.

**Comment by phated** [comment]
Completed by #147.  Will need to add some functionality to this when we implement DEBUGIN functionality, but that should be covered in that issue.
