### ISSUE TITLE
Preprocess Source to Send to PBASIC Tokenizer

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#94]
Assuming the Chrome IDE editor will naturally allow entry of non-ASCII characters (ie: Unicode code points > 255) and/or that file/database/internal storage may encode the source in multi-byte format, the source code needs to be preprocessed before sending on to the PBASIC Tokenizer.

The source that is passed to the tokenizer must be ANSI encoded (single-byte characters) where:
- Any single or multi-byte character that represents a specific ASCII character (0-255) is converted to a single-byte value (0-255), and,
- Any multi-byte character that represents a non-ASCII character (> 255) is converted to the single-byte semicolon character ';' (decimal 59, hexadecimal 3B).

The above should _only_ happen in source delivered to the tokenizer, **not** source visible to the user in any way.

NOTE: For all cases, Tokenizer's Start and Length responses refer to character counts, not byte counts, although the two interpretations may be equivalent in certain encodings.

ALSO NOTE: The semicolon character was chosen as a proper translation of a non-ASCII character for tokenizing purposes because:
1. It is not used by the PBASIC language, nor the Spin or PASM languages, to represent anything.
2. It causes a very fitting "Unrecognized character" error message, the start/length response of which naturally leads the to proper selection on-screen for the user to see in the non-translated source.

**Comment by phated** [comment]
Completed by https://github.com/parallaxinc/PBASIC-Tokenizer/pull/10 - need to update dependencies if rebuilding from source to have this feature.
